name: Close support request issues

on:
  issues:
    types:
      - labeled
      - unlabeled
      - reopened

jobs:
  support:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v2
        with:
          github-token: ${{ github.token }}
          support-label: Support request
          issue-comment: >
            Thanks, but the issue tracker is not intended for support. Please re-post it to the [Discussion](https://github.com/fuyutsuki/Texter/discussions).
          close-issue: true
          lock-issue: false